/* Copyright (C) 2016 Teng K. J.
   All rights reserved.
*/

#include "ExtWinDef.h"

std::map<UINT, LPCTSTR> WMTranslator = {
    {32768, _T("WM_APP")},
    {6, _T("WM_ACTIVATE")},
    {28, _T("WM_ACTIVATEAPP")},
    /* FIXME/CHECK: Are WM_AFX{FIRST,LAST} valid for WINVER < 0x400? */
    {864, _T("WM_AFXFIRST")},
    {895, _T("WM_AFXLAST")},
    {80, _T("WM_ASKCBFORMATNAME")},
    {75, _T("WM_CANCELJOURNAL")},
    {31, _T("WM_CANCELMODE")},
    {533, _T("WM_CAPTURECHANGED")},
    {781, _T("WM_CHANGECBCHAIN")},
    {258, _T("WM_CHAR")},
    {47, _T("WM_CHARTOITEM")},
    {34, _T("WM_CHILDACTIVATE")},
    {771, _T("WM_CLEAR")},
    {16, _T("WM_CLOSE")},
    {273, _T("WM_COMMAND")},
    {68, _T("WM_COMMNOTIFY")}, /* obsolete */
    {65, _T("WM_COMPACTING")},
    {57, _T("WM_COMPAREITEM")},
    {123, _T("WM_CONTEXTMENU")},
    {769, _T("WM_COPY")},
    {74, _T("WM_COPYDATA")},
    {1, _T("WM_CREATE")},
    {309, _T("WM_CTLCOLORBTN")},
    {310, _T("WM_CTLCOLORDLG")},
    {307, _T("WM_CTLCOLOREDIT")},
    {308, _T("WM_CTLCOLORLISTBOX")},
    {306, _T("WM_CTLCOLORMSGBOX")},
    {311, _T("WM_CTLCOLORSCROLLBAR")},
    {312, _T("WM_CTLCOLORSTATIC")},
    {768, _T("WM_CUT")},
    {259, _T("WM_DEADCHAR")},
    {45, _T("WM_DELETEITEM")},
    {2, _T("WM_DESTROY")},
    {775, _T("WM_DESTROYCLIPBOARD")},
    {537, _T("WM_DEVICECHANGE")},
    {27, _T("WM_DEVMODECHANGE")},
    {126, _T("WM_DISPLAYCHANGE")},
    {776, _T("WM_DRAWCLIPBOARD")},
    {43, _T("WM_DRAWITEM")},
    {563, _T("WM_DROPFILES")},
    {10, _T("WM_ENABLE")},
    {22, _T("WM_ENDSESSION")},
    {289, _T("WM_ENTERIDLE")},
    {529, _T("WM_ENTERMENULOOP")},
    {561, _T("WM_ENTERSIZEMOVE")},
    {20, _T("WM_ERASEBKGND")},
    {530, _T("WM_EXITMENULOOP")},
    {562, _T("WM_EXITSIZEMOVE")},
    {29, _T("WM_FONTCHANGE")},
    {135, _T("WM_GETDLGCODE")},
    {49, _T("WM_GETFONT")},
    {51, _T("WM_GETHOTKEY")},
    {127, _T("WM_GETICON")},
    {36, _T("WM_GETMINMAXINFO")},
    {13, _T("WM_GETTEXT")},
    {14, _T("WM_GETTEXTLENGTH")},
    /* FIXME/CHECK: Are WM_HANDHEL{FIRST,LAST} valid for WINVER < 0x400? */
    {856, _T("WM_HANDHELDFIRST")},
    {863, _T("WM_HANDHELDLAST")},
    {83, _T("WM_HELP")},
    {786, _T("WM_HOTKEY")},
    {276, _T("WM_HSCROLL")},
    {782, _T("WM_HSCROLLCLIPBOARD")},
    {39, _T("WM_ICONERASEBKGND")},
    {272, _T("WM_INITDIALOG")},
    {278, _T("WM_INITMENU")},
    {279, _T("WM_INITMENUPOPUP")},
    #if (_WIN32_WINNT >= 0x0501)
    {0x00FF, _T("WM_INPUT")},
    #endif
    {81, _T("WM_INPUTLANGCHANGE")},
    {80, _T("WM_INPUTLANGCHANGEREQUEST")},
    {256, _T("WM_KEYDOWN")},
    {257, _T("WM_KEYUP")},
    {8, _T("WM_KILLFOCUS")},
    {546, _T("WM_MDIACTIVATE")},
    {551, _T("WM_MDICASCADE")},
    {544, _T("WM_MDICREATE")},
    {545, _T("WM_MDIDESTROY")},
    {553, _T("WM_MDIGETACTIVE")},
    {552, _T("WM_MDIICONARRANGE")},
    {549, _T("WM_MDIMAXIMIZE")},
    {548, _T("WM_MDINEXT")},
    {564, _T("WM_MDIREFRESHMENU")},
    {547, _T("WM_MDIRESTORE")},
    {560, _T("WM_MDISETMENU")},
    {550, _T("WM_MDITILE")},
    {44, _T("WM_MEASUREITEM")},
    #if (WINVER >= 0x0500)
    {0x003D, _T("WM_GETOBJECT")},
    {0x0127, _T("WM_CHANGEUISTATE")},
    {0x0128, _T("WM_UPDATEUISTATE")},
    {0x0129, _T("WM_QUERYUISTATE")},
    {0x0125, _T("WM_UNINITMENUPOPUP")},
    {290, _T("WM_MENURBUTTONUP")},
    {0x0126, _T("WM_MENUCOMMAND")},
    {0x0124, _T("WM_MENUGETOBJECT")},
    {0x0123, _T("WM_MENUDRAG")},
    {0x0319, _T("WM_APPCOMMAND")},
    #endif
    {288, _T("WM_MENUCHAR")},
    {287, _T("WM_MENUSELECT")},
    {531, _T("WM_NEXTMENU")},
    {3, _T("WM_MOVE")},
    {534, _T("WM_MOVING")},
    {134, _T("WM_NCACTIVATE")},
    {131, _T("WM_NCCALCSIZE")},
    {129, _T("WM_NCCREATE")},
    {130, _T("WM_NCDESTROY")},
    {132, _T("WM_NCHITTEST")},
    {163, _T("WM_NCLBUTTONDBLCLK")},
    {161, _T("WM_NCLBUTTONDOWN")},
    {162, _T("WM_NCLBUTTONUP")},
    {169, _T("WM_NCMBUTTONDBLCLK")},
    {167, _T("WM_NCMBUTTONDOWN")},
    {168, _T("WM_NCMBUTTONUP")},
    #if (_WIN32_WINNT >= 0x0500)
    {171, _T("WM_NCXBUTTONDOWN")},
    {172, _T("WM_NCXBUTTONUP")},
    {173, _T("WM_NCXBUTTONDBLCLK")},
    {0x02A0, _T("WM_NCMOUSEHOVER")},
    {0x02A2, _T("WM_NCMOUSELEAVE")},
    #endif
    {160, _T("WM_NCMOUSEMOVE")},
    {133, _T("WM_NCPAINT")},
    {166, _T("WM_NCRBUTTONDBLCLK")},
    {164, _T("WM_NCRBUTTONDOWN")},
    {165, _T("WM_NCRBUTTONUP")},
    {40, _T("WM_NEXTDLGCTL")},
    {531, _T("WM_NEXTMENU")},
    {78, _T("WM_NOTIFY")},
    {85, _T("WM_NOTIFYFORMAT")},
    {0, _T("WM_NULL")},
    {15, _T("WM_PAINT")},
    {777, _T("WM_PAINTCLIPBOARD")},
    {38, _T("WM_PAINTICON")},
    {785, _T("WM_PALETTECHANGED")},
    {784, _T("WM_PALETTEISCHANGING")},
    {528, _T("WM_PARENTNOTIFY")},
    {770, _T("WM_PASTE")},
    {896, _T("WM_PENWINFIRST")},
    {911, _T("WM_PENWINLAST")},
    {72, _T("WM_POWER")},
    {536, _T("WM_POWERBROADCAST")},
    {791, _T("WM_PRINT")},
    {792, _T("WM_PRINTCLIENT")},
    {55, _T("WM_QUERYDRAGICON")},
    {17, _T("WM_QUERYENDSESSION")},
    {783, _T("WM_QUERYNEWPALETTE")},
    {19, _T("WM_QUERYOPEN")},
    {35, _T("WM_QUEUESYNC")},
    {18, _T("WM_QUIT")},
    {774, _T("WM_RENDERALLFORMATS")},
    {773, _T("WM_RENDERFORMAT")},
    {32, _T("WM_SETCURSOR")},
    {7, _T("WM_SETFOCUS")},
    {48, _T("WM_SETFONT")},
    {50, _T("WM_SETHOTKEY")},
    {128, _T("WM_SETICON")},
    {11, _T("WM_SETREDRAW")},
    {12, _T("WM_SETTEXT")},
    {26, _T("WM_SETTINGCHANGE")},
    {24, _T("WM_SHOWWINDOW")},
    {5, _T("WM_SIZE")},
    {779, _T("WM_SIZECLIPBOARD")},
    {532, _T("WM_SIZING")},
    {42, _T("WM_SPOOLERSTATUS")},
    {125, _T("WM_STYLECHANGED")},
    {124, _T("WM_STYLECHANGING")},
    {262, _T("WM_SYSCHAR")},
    {21, _T("WM_SYSCOLORCHANGE")},
    {274, _T("WM_SYSCOMMAND")},
    {263, _T("WM_SYSDEADCHAR")},
    {260, _T("WM_SYSKEYDOWN")},
    {261, _T("WM_SYSKEYUP")},
    {82, _T("WM_TCARD")},
    {794, _T("WM_THEMECHANGED")},
    {30, _T("WM_TIMECHANGE")},
    {275, _T("WM_TIMER")},
    {772, _T("WM_UNDO")},
    {1024, _T("WM_USER")},
    {84, _T("WM_USERCHANGED")},
    {46, _T("WM_VKEYTOITEM")},
    {277, _T("WM_VSCROLL")},
    {778, _T("WM_VSCROLLCLIPBOARD")},
    {71, _T("WM_WINDOWPOSCHANGED")},
    {70, _T("WM_WINDOWPOSCHANGING")},
    {26, _T("WM_WININICHANGE")},
    {256, _T("WM_KEYFIRST")},
    #if _WIN32_WINNT >= 0x0501
    {265, _T("WM_KEYLAST")},
    {265, _T("WM_UNICHAR")},
    #else
    {264, _T("WM_KEYLAST")},
    #endif
    {136, _T("WM_SYNCPAINT ")},
    {33, _T("WM_MOUSEACTIVATE")},
    {512, _T("WM_MOUSEMOVE")},
    {513, _T("WM_LBUTTONDOWN")},
    {514, _T("WM_LBUTTONUP")},
    {515, _T("WM_LBUTTONDBLCLK")},
    {516, _T("WM_RBUTTONDOWN")},
    {517, _T("WM_RBUTTONUP")},
    {518, _T("WM_RBUTTONDBLCLK")},
    {519, _T("WM_MBUTTONDOWN")},
    {520, _T("WM_MBUTTONUP")},
    {521, _T("WM_MBUTTONDBLCLK")},
    {522, _T("WM_MOUSEWHEEL")},
    {512, _T("WM_MOUSEFIRST")},
    #if (_WIN32_WINNT >= 0x0500)
    {523, _T("WM_XBUTTONDOWN")},
    {524, _T("WM_XBUTTONUP")},
    {525, _T("WM_XBUTTONDBLCLK")},
    {525, _T("WM_MOUSELAST")},
    #else
    {522, _T("WM_MOUSELAST")},
    #endif
    {0x2A1, _T("WM_MOUSEHOVER")},
    {0x2A3, _T("WM_MOUSELEAVE")},
    #if (_WIN32_WINNT >= 0x0400)
    {120, _T("WHEEL_DELTA")},
    #endif
    #if (_WIN32_WINNT >= 0x0601)
    {576, _T("WM_TOUCHMOVE")},
    {577, _T("WM_TOUCHDOWN")},
    {578, _T("WM_TOUCHUP")},
    #endif
};
